language: node_js
node_js:
  - "10.15.3"
cache:
  - npm
before_script:
  - npm i
before_deploy:
  - npm install now --no-save
script: 
  - npm run lint
  - npm run test
  - npm run build
  - now run now